### ISSUE TITLE
OMX.Exynos.avc.dec

### ISSUE THREAD

**Issue by tnanhpt** [ihmpavel/expo-video-player#13]
Error: , Encountered a fatal error during playback: com.google.android.exoplayer2.g.b$a: Decoder init failed: OMX.Exynos.avc.dec, Format(1, null, null, video/avc, null, -1, null, [1280, 720, -1.0], [-1, -1]), Fatal, Object {}
- node_modules\expo\build\logs\LogSerialization.js:166:14 in _captureConsoleStackTrace
- node_modules\expo\build\logs\LogSerialization.js:41:24 in serializeLogDataAsync$
- ... 9 more stack frames from framework internals

Hello, I am having an error when using.
Please help me! 
Thank you!

**Comment by Onytgvx** [comment]
I'm also getting this error. Though it wasn't just a couple minutes ago, I changed some code and it broke, but even going back to how it was originally now keeps it broken.

**Comment by ihmpavel** [comment]
Hi, 
the error is made during encoding on your phone (sometimes it can be also caused by unsupported video format).

Due to this, you should be able to call your function, which will show an error (instead of fullscreen default red error). See `errorCallback` in https://github.com/ihmpavel/expo-video-player#props
