### ISSUE TITLE
Can't perform a React state update on an unmounted component

### ISSUE THREAD

**Issue by xsoti** [ihmpavel/expo-video-player#140]
**Describe the bug**
When I Pause video and then navigate back from Player to previous view I got Warning: 

Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, a useEffect cleanup function

Code of player is very simple:

```
const PlayerView = ({ route, navigation }: PlayerProps) => {

  const videoHeightOffset = 12

  const { width, height } = Dimensions.get('window')
  const playerHeight = (width < height ? width : height) - videoHeightOffset - Constants.statusBarHeight
  const playerWidth = width > height ? width : height

  return (

    <VideoPlayer
      videoProps={{
        shouldPlay: true,
        resizeMode: Video.RESIZE_MODE_COVER,
        source: {
          uri: 'https://mhplayertest.s3.eu-central-1.amazonaws.com/trailerMay3.mp4',
        },
      }}
      inFullscreen={true}
      videoBackground='transparent'
      height={playerHeight}
      width={playerWidth}
    />
    
  )
}
```

**Additional infofmation:**
 - Type: Expo - Real device
 - Device: iPhone 8 Plus
 - OS: iOS 13.3.1
 - Package version "expo-video-player": "^1.5.7"
 - Expo version "expo": "~37.0.7"

**Comment by jojsj** [comment]
I have the same issue

**Comment by RubensGitHub** [comment]
same issue for me

**Comment by RubensGitHub** [comment]
Okay this took so much time for me, but at the end it was a relatively easy fix! Here a quick summary:
I first thought it was due to the different setState methods executing on an unmounted component, but that wasnt it.
The actual problem is with the timout-functions that get triggered on the unmounted component. In order to fix this, you can fork this repo and fix the timers with the react-timout library: https://github.com/plougsgaard/react-timeout .
Within the `index.tsx` file:
Add the import: 
`import ReactTimeout from 'react-timeout'`

Add `setTimeout: any` to `type Props`

And use props.setTimeout instead of setTimeout in this line:
`controlsTimer = props.setTimeout(() =>   onTimerDone(), hideControlsTimerDuration)`

Finally simply wrap the VideoPlayerDefaultProps in the last line: 
`export default ReactTimeout(VideoPlayerDefaultProps)`,

You guys are welcome to do a PR for this.
Hope this helps!

**Comment by PhillByrd2018** [comment]
Our team is also experiencing an issue when navigating away from the video player.

**Comment by MaazF94** [comment]
I'm experiencing the same issue.

**Comment by ihmpavel** [comment]
Hi everybody!

This is fixed in the latest version. Please have a look 👀
